name: Validate WDL scripts

on:
  # Trigger after the Zip workflow finishes (covers wdl_tasks changes)
  workflow_run:
    workflows: ["Build imports zips"]
    types: [completed]

  # Trigger when workflow WDLs are edited directly
  push:
    branches: [master, dev-branch]
    paths:
      - "workflows/*/*.wdl"
      - ".github/workflows/validate.yml"

  pull_request:
    paths:
      - "workflows/*/*.wdl"
      - ".github/workflows/validate.yml"

jobs:
  validate:
    name: Validate WDL workflow with WOMtool
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 2
 
      - name: Download WOMtool jar
        id: download_womtool
        run: |
          wget -q  https://github.com/broadinstitute/cromwell/releases/download/90/womtool-90.jar -O womtool.jar

      - name: Find changed workflow dirs
        id: changed_dirs
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
          base_ref=HEAD^
          else
            base_ref=${{ github.base_ref || 'HEAD^' }}
          fi

          dirs=$(git diff --name-only $base_ref HEAD \
          | grep -E 'workflows/.+(\.wdl$|imports\.zip$)' \
          | xargs -r -n1 dirname \
          | sort -u)

          if [ -n "$dirs" ]; then
          {
              echo "dirs<<EOF"
              echo "$dirs"
              echo "EOF"
          } >> $GITHUB_OUTPUT
          fi

      - name: Unzip imports if present
        if: steps.changed_dirs.outputs.dirs != ''
        run: |
          # turn any newlines in the output into spaces
          DIRS="${{ steps.changed_dirs.outputs.dirs }}"
          DIRS="${DIRS//$'\n'/ }"

          for d in $DIRS; do
            if [ -f "$d/imports.zip" ]; then
              echo "Unzipping $d/imports.zip"
              unzip -o "$d/imports.zip" -d "$d/imports"
            fi
          done
          
      - name: Validate changed workflows
        if: steps.changed_dirs.outputs.dirs != ''
        run: |
          for d in ${{ steps.changed_dirs.outputs.dirs }}; do
            for w in $d/*.wdl; do
              echo "Validating $w"
              java -jar womtool.jar validate "$w" || exit 1
            done
          done
